# Tugas 2 - Diskritisasi 
### Nama : Nella Adrisia Hartono
### Nim : 200411100107
###Kelas : B

Carilah data yang bertipe numerik ( data klassifikasi)

1. Lakukan proses diskritisasi dengan equal width dan equal frequency

2. Lakukan proses diskritisasi  dengan basis entropy

##**Topik** Data:

Pengelompokkan jenis Bunga Iris berdasrakan panjang dan lebar kelopak serta daun kelopak

In [ ]:
#mengimpor atau mengambil library pada pandas, numpy, seaborn, dan matplotlib
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

mengambil dataset iris yang sudah di internet kemudian diupload di repositori github yang sudah dibuat dan menyalin link raw dataset yang ada dalam repo untuk dibuka dengan cara berikut

In [ ]:
url = 'https://raw.githubusercontent.com/nellaadrs/datamining/gh-pages/Iris.csv'
dataset = pd.read_csv(url)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
dataset

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

# **1. Equal Width Interval**

Equal Width Interval merupakan discretization yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar

In [ ]:
panjang_kelopak = dataset[["SepalLengthCm"]]
lebar_kelopak = dataset[["SepalWidthCm"]]
panjang_daunkelopak = dataset[["PetalLengthCm"]]
lebar_daunkelopak = dataset[["PetalWidthCm"]]

membuat fungsi **cut** yang digunakan untuk mencari interval menggunakan metode Equal-Width-Intervals

In [ ]:
def cut(col, k):
  intervals = pd.cut(dataset[col], k).value_counts().index.to_list()
  return [[interval.left, interval.right] for interval in intervals]

In [ ]:
def toCategory(list_interval, col):
  # get length interval
  length = len(list_interval)

  # sorting interval
  sort_interval = np.sort(list_interval, axis=0)

  # get category from interval
  categories = np.array([chr(65+i) for i in range(length)])[:, None]

  # Combine into interval data
  intervals = np.hstack((sort_interval, categories))

  # operate all data
  newCol = []
  for i, row in dataset.iterrows():
    d = row[col]
    for interval in intervals:
      if d >= interval[0].astype(float) and d <= interval[1].astype(float):
        newCol.append(interval[2])
        break

  # return new column category
  return np.array(newCol, dtype=str)

mencari interval dengan membaginya menjadi 3 bagian

In [ ]:
interval_panjang_kelopak = cut("SepalLengthCm", 3)
interval_lebar_kelopak = cut("SepalWidthCm", 3)
interval_panjang_daunkelopak = cut("PetalLengthCm", 3)
interval_lebar_daunkelopak = cut("PetalWidthCm", 3)

print("Interval_panjang_kelopak = ", interval_panjang_kelopak)
print("Interval_lebar_kelopak = ", interval_lebar_kelopak)
print("Interval_panjang_daunkelopak = ", interval_panjang_daunkelopak)
print("Interval_lebar_daunkelopak = ", interval_lebar_daunkelopak)

Interval_panjang_kelopak =  [[5.5, 6.7], [4.296, 5.5], [6.7, 7.9]]
Interval_lebar_kelopak =  [[2.8, 3.6], [1.998, 2.8], [3.6, 4.4]]
Interval_panjang_daunkelopak =  [[2.967, 4.933], [0.994, 2.967], [4.933, 6.9]]
Interval_lebar_daunkelopak =  [[0.9, 1.7], [0.0976, 0.9], [1.7, 2.5]]

In [ ]:
panjang_kelopak["category"] = toCategory(interval_panjang_kelopak, "SepalLengthCm")
lebar_kelopak["category"] = toCategory(interval_lebar_kelopak, "SepalWidthCm")
panjang_daunkelopak["category"] = toCategory(interval_panjang_daunkelopak, "PetalLengthCm")
lebar_daunkelopak["category"] = toCategory(interval_lebar_daunkelopak, "PetalWidthCm")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
print('Pengelompokan panjang kelopak bunga iris')
display(panjang_kelopak)

Pengelompokan panjang kelopak bunga iris

     SepalLengthCm category
0              5.1        A
1              4.9        A
2              4.7        A
3              4.6        A
4              5.0        A
..             ...      ...
145            6.7        B
146            6.3        B
147            6.5        B
148            6.2        B
149            5.9        B

[150 rows x 2 columns]

In [ ]:
print('Pengelompokan lebar kelopak bunga iris')
display(lebar_kelopak)

Pengelompokan lebar kelopak bunga iris

     SepalWidthCm category
0             3.5        B
1             3.0        B
2             3.2        B
3             3.1        B
4             3.6        B
..            ...      ...
145           3.0        B
146           2.5        A
147           3.0        B
148           3.4        B
149           3.0        B

[150 rows x 2 columns]

In [ ]:
print('Pengelompokan panjang daun kelopak bunga iris')
display(panjang_daunkelopak)

Pengelompokan panjang daun kelopak bunga iris

     PetalLengthCm category
0              1.4        A
1              1.4        A
2              1.3        A
3              1.5        A
4              1.4        A
..             ...      ...
145            5.2        C
146            5.0        C
147            5.2        C
148            5.4        C
149            5.1        C

[150 rows x 2 columns]

In [ ]:
print("Pengelompokan lebar daun kelopak bunga iris")
display(lebar_daunkelopak)

Pengelompokan lebar daun kelopak bunga iris

     PetalWidthCm category
0             0.2        A
1             0.2        A
2             0.2        A
3             0.2        A
4             0.2        A
..            ...      ...
145           2.3        C
146           1.9        C
147           2.0        C
148           2.3        C
149           1.8        C

[150 rows x 2 columns]

# **2. Equal Frequency Intervals**

Equal Frequency Intervals merupakan discretization yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota yang kurang lebih sama besar.

Pandas menyediakan method qcut untuk mencari nilai interval dari Equal_Frequency Intervals

In [ ]:
def qcut(col, k):
  intervals = pd.qcut(dataset[col], k).value_counts().index.to_list()
  return [[interval.left, interval.right] for interval in intervals]

mencari interval dengan membaginya menjadi 3 bagian

In [ ]:
q_interval_panjang_kelopak = qcut("SepalLengthCm", 3)
q_interval_lebar_kelopak = qcut("SepalWidthCm", 3)
q_interval_panjang_daunkelopak = qcut("PetalLengthCm", 3)
q_interval_lebar_daunkelopak = qcut("PetalWidthCm", 3)

print("Interval_panjang_kelopak = ", q_interval_panjang_kelopak)
print("Interval_lebar_kelopak = ", q_interval_lebar_kelopak)
print("Interval_panjang_daunkelopak = ", q_interval_panjang_daunkelopak)
print("Interval_lebar_daunkelopak = ", q_interval_lebar_daunkelopak)

Interval_panjang_kelopak =  [[5.4, 6.3], [4.2989999999999995, 5.4], [6.3, 7.9]]
Interval_lebar_kelopak =  [[1.999, 2.9], [2.9, 3.2], [3.2, 4.4]]
Interval_panjang_daunkelopak =  [[2.633, 4.9], [0.999, 2.633], [4.9, 6.9]]
Interval_lebar_daunkelopak =  [[0.867, 1.6], [0.099, 0.867], [1.6, 2.5]]

In [ ]:
#menampilkan hasil kategori

panjang_kelopak["category"] = toCategory(q_interval_panjang_kelopak, "SepalLengthCm")
lebar_kelopak["category"] = toCategory(q_interval_lebar_kelopak, "SepalWidthCm")
panjang_daunkelopak["category"] = toCategory(q_interval_panjang_daunkelopak, "PetalLengthCm")
lebar_daunkelopak["category"] = toCategory(q_interval_lebar_daunkelopak, "PetalWidthCm")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
print("Pengelompokkan panjang kelopak bunga iris")
display (panjang_kelopak)

Pengelompokkan panjang kelopak bunga iris

     SepalLengthCm category
0              5.1        A
1              4.9        A
2              4.7        A
3              4.6        A
4              5.0        A
..             ...      ...
145            6.7        C
146            6.3        B
147            6.5        C
148            6.2        B
149            5.9        B

[150 rows x 2 columns]

In [ ]:
print("Pengelompokkan lebar kelopak bunga iris")
display (lebar_kelopak)

Pengelompokkan lebar kelopak bunga iris

     SepalWidthCm category
0             3.5        C
1             3.0        B
2             3.2        B
3             3.1        B
4             3.6        C
..            ...      ...
145           3.0        B
146           2.5        A
147           3.0        B
148           3.4        C
149           3.0        B

[150 rows x 2 columns]

In [ ]:
print("Pengelompokkan panjang daun kelopak bunga iris")
display (panjang_daunkelopak)

Pengelompokkan panjang daun kelopak bunga iris

     PetalLengthCm category
0              1.4        A
1              1.4        A
2              1.3        A
3              1.5        A
4              1.4        A
..             ...      ...
145            5.2        C
146            5.0        C
147            5.2        C
148            5.4        C
149            5.1        C

[150 rows x 2 columns]

In [ ]:
print("Pengelompokkan lebar daun kelopak bunga iris")
display (lebar_daunkelopak)

Pengelompokkan lebar daun kelopak bunga iris

     PetalWidthCm category
0             0.2        A
1             0.2        A
2             0.2        A
3             0.2        A
4             0.2        A
..            ...      ...
145           2.3        C
146           1.9        C
147           2.0        C
148           2.3        C
149           1.8        C

[150 rows x 2 columns]

# **3. Entropy**

entropi adalah nilai yang menyatukan ukuran ketidakpastian (impurity) dan attribur sari suatu onjek data dalam satuan bit

pada peugasan ini akan menggunakan data panjang kelopak (sepal length) sembagi sampel perhitungan

In [ ]:
sampel = dataset [["SepalLengthCm"]]
sampel.describe ()

       SepalLengthCm
count     150.000000
mean        5.843333
std         0.828066
min         4.300000
25%         5.100000
50%         5.800000
75%         6.400000
max         7.900000

In [ ]:
#membuat kategori random untuk semua data

np.random.seed(0)
sampel["category"] = np.where(np.random.choice(2, sampel.shape[0]) < 1, "A", "B")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
print('Pengelompokan data uji dengan kategori random')
sampel

Pengelompokan data uji dengan kategori random

     SepalLengthCm category
0              5.1        A
1              4.9        B
2              4.7        B
3              4.6        A
4              5.0        B
..             ...      ...
145            6.7        A
146            6.3        B
147            6.5        B
148            6.2        B
149            5.9        B

[150 rows x 2 columns]

membuat fungsi **getOverCategory** yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [ ]:
def getOverCategory(col):
  group = sampel.loc[:, :].groupby("category").count()
  a = group.loc["A", col]
  b = group.loc["B", col]
  return (a, b, a+b)

fungsi splitter digunakan untuk membuat split antara value yang telah ditentukan lalu mengembalikan data yang telah dipisahkan

In [ ]:
def splitter(value:float, col:str)->tuple:
  # get data less and greater from value
  less = sampel[sampel[col] <= value]
  greater = sampel[sampel[col] > value]

  # calculate into category for each data
  less_group = less.loc[:, :].groupby("category").count()
  greater_group = greater.loc[:, :].groupby("category").count()

  # get value based on category
  less_category_A = less_group.loc["A", col] 
  less_category_B = less_group.loc["B", col] 
  greater_category_A = greater_group.loc["A", col] 
  greater_category_B = greater_group.loc["B", col] 

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

Rumus Mencari Entropy:
$$ Entropy (D_1) = - Î£ _1^n\ pi \log_2 \ pi  $$

In [ ]:
def entropy (d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2])
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2])
  return np.sum([r1, r2]) * -1

In [ ]:
#membuat fungsi info

def info (d):
  r1 = (d[0][2] / sampel.shape [0]) * entropy (d[0])
  r2 = (d[1][2] / sampel.shape [0]) * entropy (d[1])
  return r1 + r2

Membuat fungsi gain untuk menghitung selisih antara entropy awal dengan yang baru

Rumus Gain:

$$ Gain(Enew) = (Einitial) - (Enew) $$

In [ ]:
def gain(Einitial, Enew):
  return Einitial - Enew

In [ ]:
D = getOverCategory("SepalLengthCm")
entropy_d = entropy(D)
print("D = ",D)
print("Entropy D = ", entropy_d)

D =  (68, 82, 150)
Entropy D =  0.993707106604508

Melakukan beberapa tes split untuk mencari hasil dan informasi yang terbaik

In [ ]:
#Tes Pertama : Split 1:4.4

split1 = splitter (4.4, "SepalLengthCm")
info_split1 = info (split1)

print("Gain = ",  gain (entropy_d, info_split1))

Gain =  0.003488151753460178

In [ ]:
#Tes Pertama : Split 2:5.5

split2 = splitter (5.5, "SepalLengthCm")
info_split2 = info (split2)

print("Gain = ",  gain (entropy_d, info_split2))

Gain =  0.012302155146638905

In [ ]:
#Tes Pertama : Split 3:7.0

split3 = splitter (7.0, "SepalLengthCm")
info_split3 = info (split3)

print("Gain = ",  gain (entropy_d, info_split3))

Gain =  0.0005490214732508658

Kesimpulan

Dari Seluruh hasil percobaan tes split yang telah dilakukan, maka diperoleh hasil split terbaik adalah split 3 yang memberikan keuntungan informasi terbesar adalah 0.0005490214732508658, karena hasil tes split 3 memiliki nilai split yang terendah